url https://demo7.vtexperts.com/vtigercrm7demo/index.php
un  demo
pwd demo
browser firef
url1 https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
username Admin
password admin123
url2 https://demo.vtiger.com/vtigercrm/index.php
Username admin
Password admin
